Feature attack ability
AJ-Game/AJGame pull request #12
Opened 2023-10-10 23:05 UTC by aimalesa

Attack ability implemented

2023-10-10 23:09 UTC, jiggly-jo requested changes
Change sword attack damage to 1.

2023-10-10 23:11 UTC, jiggly-jo requested changes
Change attack damage to 1

2023-10-10 23:11 UTC, jiggly-jo commented on Assets/SwordAttack.cs
> +    public float damage = 3;
Change attack damage to 1

2023-10-11 00:51 UTC, aimalesa commented on Assets/SwordAttack.cs
> +    public float damage = 3;
Damage has been reduced to 1.

2023-10-11 04:12 UTC, jiggly-jo commented
good work

2023-10-11 04:12 UTC, jiggly-jo approved these changes
nice

2023-10-11 04:12 UTC, merged